- name: Launching Echo app and Search app
  hosts: ta_worker
  tasks: 
    - name: Search process
      ignore_errors: yes
      shell: "if pgrep search-app; then pkill search-app; fi"

    - name: Search process
      ignore_errors: yes
      shell: "if pgrep echo-system; then pkill echo-system; fi"


- name: Launching web server
  hosts: ta_web_server
  tasks:
    - name: Search process
      ignore_errors: yes
      shell: "if sudo pgrep frontend; then sudo pkill frontend; fi"
